### ISSUE TITLE
Could iskeyword dollar be configurable?

### ISSUE THREAD

**Issue by peterbabic** [yaegassy/coc-intelephense#42]
I have traced my issue around to lines https://github.com/yaegassy/coc-intelephense/blob/548665c0332af6dbdb4aee77ef2f01e7c7071c01/src/index.ts#L62

There, the plugin is setting iskeyword dollar sign to `+=$`, which is exact opposite of what I prefer, I would like it to be `-=$` to keep the dollar sign in place.

Is this there because of some other functionality depends on it or is this just an author's preference?

How to disable/override/configure this behavior please?

**Comment by yaegassy** [comment]
Added the setting "intelephense.client.disableAddIskeyword". Set `"intelephense.client.disableAddIskeyword": true` in `coc-setting.json`.

> Is this there because of some other functionality depends on it or is this just an author's preference?
I think it was because there is a feature that depends on the `$` being added to `iskeyword`, but I forget which one. I know it is probably a completion or hover related feature, but please let us know if you encounter any problems. We'll try to adjust in another way.
